### ISSUE TITLE
Move CLI tracking files to Library API

### ISSUE THREAD

**Issue by Deathspike** [Deathspike/animesync#51]
The Library API launched in `v2.0.0` does not include the CLI tracking files. 

- [ ] Add tracking status to episode listing.
- [ ] Generate tracking file when a download has succeeded.
- [ ] Delete tracking file when an episode is deleted.
- [ ] Migrate CLI to newly added APIs.
